name: Publish module to PowerShellGallery
on:
  release:
    types: [published]
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Publish Module
      uses: pcgeek86/publish-powershell-module-action@v20
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}