name: Publish module to PowerShellGallery
on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PS_GALLERY_KEY: ${{secrets.PS_GALLERY_KEY}}
    steps:
    - uses: actions/checkout@v3
      with:
        path: "MSPToolBox"
    - name: Publish Module
      shell: pwsh
      run: |
        $modulePath = Get-ChildItem -Recurse -Filter '*.psd1' | Select-Object -Unique -ExpandProperty Directory
        $publishSplat = @{Path = $modulePath; NuGetApiKey = $env:PS_GALLERY_KEY}
        Publish-Module @publishSplat -Verbose